import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
    en: {
        explore: "Explore",
        categories: "Categories",
        ride: "Ride",
        food: "Food",
        hotels: "Hotels",
        partners: "Partners",
        clubs: "Clubs",
        events: "Events",
        innerCircle: "Inner Circle",
        lifestyleHub: "Lifestyle Hub",
        fairSplit: "Fair-Split Pro",
        execute: "Execute Split",
        totalBill: "Total Bill",
        stealth: "Stealth",
        live: "Live",
        manageCircle: "Manage Circle",
        viewReceipt: "View Social Receipt",
        discover: "Discover",
        search: "Search matrix...",
        welcome: "Welcome back",
        initiate: "GrienRide",
        "Dashboard": "Dashboard",
        "Room Service": "Room Service",
        "Bottle Service": "Bottle Service",
        "Ticket Orders": "Ticket Orders",
        "Live Orders": "Live Orders",
        "Ticket Hub": "Ticket Hub",
        "Room Hub": "Room Hub",
        "Team Hub": "Team Hub",
        "Nightly Audit": "Nightly Audit",
        "Cover Revenue": "Cover Revenue",
        "Financials": "Financials",
        "Compliance": "Compliance",
        "Marketing Hub": "Marketing Hub",
        "Reputation Hub": "Reputation Hub",
        "AI Strategic Hub": "AI Strategic Hub",
        "Fleet Control Hub": "Fleet Control Hub",
        "Sitting": "Sitting",
        "Menu Catalog": "Menu Catalog",

        // Profile & Account Navigation Menu
        bankHub: "Bank Hub",
        languagePreferences: "Language Preferences",
        favoriteDrivers: "Favorite Drivers (FTD)",
        rideHistory: "Ride History",
        accountSecurity: "Account & Security",
        familyHub: "Family Hub",
        helpSupport: "Help & Support",
        logout: "Logout",
        premiumStatus: "PREMIUM STATUS",
        languageHub: "Language Hub",
        saved: "Saved",
        parentPortal: "Parent Portal",

        // Order Tracker & Ticket Voucher
        yourTicket: "YOUR TICKET",
        ticketStatus: "Ticket Status",
        paymentStatus: "Payment Status",
        totalCharged: "Total Charged",
        confirmed: "CONFIRMED",
        paid: "PAID",
        unpaid: "UNPAID",
        bookingStatus: "Booking Status",
        orderStatus: "Order Status",
        checkIn: "Check-In",
        checkOut: "Check-Out",
        roomQuantity: "Room / Type",
        guestQuantity: "Guests",
        billing: "Billing",
        bookingId: "Booking ID",
        emailVoucherTitle: "E-Mail Reservation Confirmation",
        emailStadiumVoucherTitle: "E-Mail Stadium E-Ticket Confirmation",
        officialVoucher: "Official Hotel Voucher",
        officialStadiumVoucher: "Official Stadium E-Ticket Voucher",
        stadiumTicketConfirmed: "Stadium E-Ticket Confirmed",
        opticalScanKey: "Optical Stadium Scan Key (Gate Entry)",
        backToMenu: "Back to Menu",
        closeMission: "Close Mission",
        closeTable: "Close Table",
        closeFolio: "Close Folio",
        settleTab: "Settle Tab",
        sendEmailConfirmation: "Send Confirmation via E-Mail",
        emailConfirmationSent: "Confirmation Sent via E-Mail ✓",
        sendingEmail: "Sending Confirmation...",
        sendEmailNow: "Send E-Mail Now",
        resendEmail: "Resend to E-Mail",
        close: "Close",
        recipient: "Recipient",
        sender: "Sender",
        subject: "Subject",
        reservationConfirmed: "Reservation Confirmed",

        // Shuttle & Driver Hub
        shuttleServiceHub: "Shuttle Service Hub",
        acceptRide: "Accept Ride",
        accepted: "Accepted",
        passengers: "Passengers",
        luggage: "Luggage",
        
        // Social Hub
        socialHub: "Social Hub",
        uploadMedia: "Upload Media",
        livePreview: "Live Feed Preview",
        publishPost: "Publish Post"
    },
    de: { // High-quality German
        explore: "Erkunden",
        categories: "Kategorien",
        ride: "Fahrt",
        food: "Essen",
        hotels: "Hotels",
        partners: "Partner",
        clubs: "Clubs",
        events: "Events",
        innerCircle: "Freundeskreis",
        lifestyleHub: "Lifestyle Hub",
        fairSplit: "Fair-Split Pro",
        execute: "Split ausführen",
        totalBill: "Gesamtbetrag",
        stealth: "Privat",
        live: "Live",
        manageCircle: "Kreis verwalten",
        viewReceipt: "Beleg anzeigen",
        discover: "Entdecken",
        search: "Netzwerk durchsuchen...",
        welcome: "Willkommen zurück",
        initiate: "GrienRide",
        "Dashboard": "Übersicht",
        "Room Service": "Zimmerservice",
        "Bottle Service": "Flaschenservice",
        "Ticket Orders": "Ticket-Bestellungen",
        "Live Orders": "Live-Bestellungen",
        "Ticket Hub": "Ticket-Zentrum",
        "Room Hub": "Zimmer-Zentrum",
        "Team Hub": "Team-Zentrum",
        "Nightly Audit": "Nachtprüfung",
        "Cover Revenue": "Eintrittsumsatz",
        "Financials": "Finanzen",
        "Compliance": "Compliance",
        "Marketing Hub": "Marketing-Zentrum",
        "Reputation Hub": "Reputation-Zentrum",
        "AI Strategic Hub": "KI-Strategie",
        "Fleet Control Hub": "Flottenzentrum",
        "Sitting": "Sitzordnung",
        "Menu Catalog": "Menükatalog",

        // Profile & Account Navigation Menu
        bankHub: "Bank Hub",
        languagePreferences: "Spracheinstellungen",
        favoriteDrivers: "Lieblingsfahrer (FTD)",
        rideHistory: "Fahrtverlauf",
        accountSecurity: "Konto & Sicherheit",
        familyHub: "Familien-Hub",
        helpSupport: "Hilfe & Support",
        logout: "Abmelden",
        premiumStatus: "PREMIUM STATUS",
        languageHub: "Sprachen-Zentrum",
        saved: "Gespeichert",
        parentPortal: "Eltern-Portal",

        // Order Tracker & Ticket Voucher
        yourTicket: "DEIN TICKET",
        ticketStatus: "Ticket-Status",
        paymentStatus: "Zahlungsstatus",
        totalCharged: "Gesamtsumme",
        confirmed: "BESTÄTIGT",
        paid: "BEZAHLT",
        unpaid: "OFFEN",
        bookingStatus: "Buchungsstatus",
        orderStatus: "Bestellstatus",
        checkIn: "Check-In",
        checkOut: "Check-Out",
        roomQuantity: "Zimmer-Anzahl / Typ",
        guestQuantity: "Gäste-Anzahl",
        billing: "Abrechnung",
        bookingId: "Buchungs-ID",
        emailVoucherTitle: "E-Mail Reservierungsbestätigung",
        emailStadiumVoucherTitle: "E-Mail Stadion E-Ticket Bestätigung",
        officialVoucher: "Offizieller Hotel-Voucher",
        officialStadiumVoucher: "Offizieller Stadion E-Ticket Voucher",
        stadiumTicketConfirmed: "Stadion E-Ticket Bestätigt",
        opticalScanKey: "Optischer Stadion-Scan Key (Stadion-Zugang)",
        backToMenu: "Zurück zum Menü",
        closeMission: "Mission beenden",
        closeTable: "Tisch schließen",
        closeFolio: "Rechnung beenden",
        settleTab: "Rechnung begleichen",
        sendEmailConfirmation: "Bestätigung per E-Mail senden",
        emailConfirmationSent: "Bestätigung per E-Mail gesendet ✓",
        sendingEmail: "Bestätigung wird gesendet...",
        sendEmailNow: "E-Mail jetzt senden",
        resendEmail: "Erneut an E-Mail senden",
        close: "Schließen",
        recipient: "Empfänger",
        sender: "Absender",
        subject: "Betreff",
        reservationConfirmed: "Reservierung Bestätigt",

        // Shuttle & Driver Hub
        shuttleServiceHub: "Shuttle-Service Hub",
        acceptRide: "Fahrt akzeptieren",
        accepted: "Akzeptiert",
        passengers: "Fahrgäste",
        luggage: "Gepäck",

        // Social Hub
        socialHub: "Social Hub",
        uploadMedia: "Medien hochladen",
        livePreview: "Live-Feed Vorschau",
        publishPost: "Beitrag veröffentlichen"
    },
    fa: { // Farsi / Dari
        explore: "جستجو",
        categories: "دسته‌بندی‌ها",
        ride: "سفر",
        food: "غذا",
        hotels: "هتل‌ها",
        partners: "شرکا",
        clubs: "کلوب‌ها",
        events: "رویدادها",
        innerCircle: "حلقه دوستان",
        lifestyleHub: "مرکز لایف‌استایل",
        fairSplit: "تقسیم عادلانه",
        execute: "اجرای تقسیم",
        totalBill: "کل صورتحساب",
        stealth: "مخفی",
        live: "زنده",
        manageCircle: "مدیریت حلقه",
        viewReceipt: "مشاهده رسید",
        discover: "کشف کردن",
        search: "جستجو در شبکه...",
        welcome: "خوش آمدید",
        initiate: "سفر سبز",
        "Dashboard": "داشبورد",
        "Room Service": "سرویس اتاق",
        "Bottle Service": "سرویس نوشیدنی",
        "Ticket Orders": "سفارشات بلیت",
        "Live Orders": "سفارشات زنده",
        "Ticket Hub": "مرکز بلیت",
        "Room Hub": "مرکز اتاق",
        "Team Hub": "مرکز تیم",
        "Nightly Audit": "حسابرسی شبانه",
        "Cover Revenue": "درآمد ورودی",
        "Financials": "امور مالی",
        "Compliance": "انطباق",
        "Marketing Hub": "مرکز بازاریابی",
        "Reputation Hub": "مرکز اعتبار",
        "AI Strategic Hub": "استراتژی هوش مصنوعی",
        "Fleet Control Hub": "مدیریت ناوگان",
        "Sitting": "چیدمان صندلی",
        "Menu Catalog": "کاتالوگ منو",

        // Profile & Account Navigation Menu
        bankHub: "مرکز بانکی",
        languagePreferences: "تنظیمات زبان",
        favoriteDrivers: "رانندگان محبوب",
        rideHistory: "تاریخچه سفرها",
        accountSecurity: "حساب و امنیت",
        familyHub: "مرکز خانواده",
        helpSupport: "کمک و پشتیبانی",
        logout: "خروج",
        premiumStatus: "وضعیت ویژه",
        languageHub: "مرکز زبان‌ها",
        saved: "ذخیره شده",
        parentPortal: "پورتال والدین",

        // Order Tracker & Ticket Voucher
        yourTicket: "بلیت شما",
        ticketStatus: "وضعیت بلیت",
        paymentStatus: "وضعیت پرداخت",
        totalCharged: "مبلغ کل",
        confirmed: "تایید شده",
        paid: "پرداخت شده",
        unpaid: "پرداخت نشده",
        bookingStatus: "وضعیت رزرو",
        orderStatus: "وضعیت سفارش",
        checkIn: "ورود",
        checkOut: "خروج",
        roomQuantity: "تعداد / نوع اتاق",
        guestQuantity: "تعداد مهمانان",
        billing: "صورتحساب",
        bookingId: "شناسه رزرو",
        emailVoucherTitle: "تاییدیه رزرو ایمیلی",
        emailStadiumVoucherTitle: "تاییدیه ایمیل e-ticket استادیوم",
        officialVoucher: "ووچر رسمی هتل",
        officialStadiumVoucher: "ووچر رسمی e-ticket استادیوم",
        stadiumTicketConfirmed: "e-ticket استادیوم تایید شد",
        opticalScanKey: "کلید اسکن اپتیکال استادیوم (ورود)",
        backToMenu: "بازگشت به منو",
        closeMission: "پایان ماموریت",
        closeTable: "بستن میز",
        closeFolio: "بستن صورتحساب",
        settleTab: "تسویه حساب",
        sendEmailConfirmation: "ارسال تاییدیه با ایمیل",
        emailConfirmationSent: "تاییدیه با ایمیل ارسال شد ✓",
        sendingEmail: "در حال ارسال تاییدیه...",
        sendEmailNow: "ارسال ایمیل",
        resendEmail: "ارسال مجدد به ایمیل",
        close: "بستن",
        recipient: "گیرنده",
        sender: "فرستنده",
        subject: "موضوع",
        reservationConfirmed: "رزرو تایید شد",

        // Shuttle & Driver Hub
        shuttleServiceHub: "مرکز شاتل",
        acceptRide: "پذیرش سفر",
        accepted: "پذیرفته شد",
        passengers: "مسافران",
        luggage: "چمدان‌ها",

        // Social Hub
        socialHub: "مرکز اجتماعی",
        uploadMedia: "بارگذاری رسانه",
        livePreview: "پیش‌نمایش زنده",
        publishPost: "انتشار پست"
    },
    fr: { // French
        explore: "Explorer",
        categories: "Catégories",
        ride: "Course",
        food: "Nourriture",
        hotels: "Hôtels",
        partners: "Partenaires",
        clubs: "Clubs",
        events: "Événements",
        innerCircle: "Cercle Intime",
        lifestyleHub: "Lifestyle Hub",
        fairSplit: "Fair-Split Pro",
        execute: "Exécuter le Partage",
        totalBill: "Facture Totale",
        stealth: "Discret",
        live: "En Direct",
        manageCircle: "Gérer le Cercle",
        viewReceipt: "Voir le Reçu",
        discover: "Découvrir",
        search: "Chercher...",
        welcome: "Bon retour",
        initiate: "GrienRide",
        "Dashboard": "Tableau de bord",
        "Room Service": "Service en chambre",
        "Bottle Service": "Service bouteille",
        "Ticket Orders": "Commandes de billets",
        "Live Orders": "Commandes en direct",
        "Ticket Hub": "Hub de billets",
        "Room Hub": "Hub des chambres",
        "Team Hub": "Hub d'équipe",
        "Nightly Audit": "Audit nocturne",
        "Cover Revenue": "Revenu d'entrée",
        "Financials": "Finances",
        "Compliance": "Conformité",
        "Marketing Hub": "Hub Marketing",
        "Reputation Hub": "Hub Réputation",
        "AI Strategic Hub": "IA Stratégique",
        "Fleet Control Hub": "Gestion de flotte",
        "Sitting": "Disposition",
        "Menu Catalog": "Catalogue du menu",

        // Profile & Account Navigation Menu
        bankHub: "Hub Bancaire",
        languagePreferences: "Préférences de Langue",
        favoriteDrivers: "Chauffeurs Favoris (FTD)",
        rideHistory: "Historique des Courses",
        accountSecurity: "Compte & Sécurité",
        familyHub: "Hub Familial",
        helpSupport: "Aide & Support",
        logout: "Déconnexion",
        premiumStatus: "STATUT PREMIUM",
        languageHub: "Hub des Langues",
        saved: "Enregistré",
        parentPortal: "Portail Parents",

        // Order Tracker & Ticket Voucher
        yourTicket: "VOTRE BILLET",
        ticketStatus: "Statut du Billet",
        paymentStatus: "Statut du Paiement",
        totalCharged: "Total Facturé",
        confirmed: "CONFIRMÉ",
        paid: "PAYÉ",
        unpaid: "NON PAYÉ",
        bookingStatus: "Statut de Réservation",
        orderStatus: "Statut de Commande",
        checkIn: "Arrivée",
        checkOut: "Départ",
        roomQuantity: "Chambre / Type",
        guestQuantity: "Nombre de Clients",
        billing: "Facturation",
        bookingId: "ID de Réservation",
        emailVoucherTitle: "Confirmation par E-Mail",
        emailStadiumVoucherTitle: "Confirmation E-Ticket Stade par E-Mail",
        officialVoucher: "Voucher Officiel d'Hôtel",
        officialStadiumVoucher: "Voucher Officiel E-Ticket Stade",
        stadiumTicketConfirmed: "E-Ticket Stade Confirmé",
        opticalScanKey: "Clé de scan optique (Entrée Stade)",
        backToMenu: "Retour au Menu",
        closeMission: "Fermer la Mission",
        closeTable: "Fermer la Table",
        closeFolio: "Fermer la Note",
        settleTab: "Régler l'Addition",
        sendEmailConfirmation: "Envoyer Confirmation par E-Mail",
        emailConfirmationSent: "Confirmation Envoyée par E-Mail ✓",
        sendingEmail: "Envoi de la confirmation...",
        sendEmailNow: "Envoyer l'E-Mail Maintenant",
        resendEmail: "Renvoyer par E-Mail",
        close: "Fermer",
        recipient: "Destinataire",
        sender: "Expéditeur",
        subject: "Objet",
        reservationConfirmed: "Réservation Confirmée",

        // Shuttle & Driver Hub
        shuttleServiceHub: "Centre Navette",
        acceptRide: "Accepter la Course",
        accepted: "Accepté",
        passengers: "Passagers",
        luggage: "Bagages",

        // Social Hub
        socialHub: "Hub Social",
        uploadMedia: "Télécharger des Médias",
        livePreview: "Aperçu en Direct",
        publishPost: "Publier"
    }
};

export const LanguageProvider = ({ children }) => {
    const [lang, setLang] = useState('en');
    const [dir, setDir] = useState('ltr');

    useEffect(() => {
        if (lang === 'fa') {
            setDir('rtl');
            document.documentElement.dir = 'rtl';
        } else {
            setDir('ltr');
            document.documentElement.dir = 'ltr';
        }
    }, [lang]);

    const t = (key) => {
        return translations[lang]?.[key] || translations['en']?.[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ lang, setLang, t, dir }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
